// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/thinkit/AdminDashboard.tsx": () => import("../components/mockups/thinkit/AdminDashboard.tsx"),
  "./components/mockups/thinkit/Cart.tsx": () => import("../components/mockups/thinkit/Cart.tsx"),
  "./components/mockups/thinkit/Categories.tsx": () => import("../components/mockups/thinkit/Categories.tsx"),
  "./components/mockups/thinkit/Checkout.tsx": () => import("../components/mockups/thinkit/Checkout.tsx"),
  "./components/mockups/thinkit/Home.tsx": () => import("../components/mockups/thinkit/Home.tsx"),
  "./components/mockups/thinkit/Orders.tsx": () => import("../components/mockups/thinkit/Orders.tsx"),
  "./components/mockups/thinkit/ProductDetail.tsx": () => import("../components/mockups/thinkit/ProductDetail.tsx"),
  "./components/mockups/thinkit/ProductListing.tsx": () => import("../components/mockups/thinkit/ProductListing.tsx"),
  "./components/mockups/thinkit/Profile.tsx": () => import("../components/mockups/thinkit/Profile.tsx"),
  "./components/mockups/thinkit/ProfileSetup.tsx": () => import("../components/mockups/thinkit/ProfileSetup.tsx"),
  "./components/mockups/thinkit/SignIn.tsx": () => import("../components/mockups/thinkit/SignIn.tsx"),
  "./components/mockups/thinkit/Splash.tsx": () => import("../components/mockups/thinkit/Splash.tsx"),
  "./components/mockups/thinkit/Subcategory.tsx": () => import("../components/mockups/thinkit/Subcategory.tsx")
};
